package cmd

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"

	"github.com/Giancarlos/guardrails/internal/db"
	"github.com/Giancarlos/guardrails/internal/models"
)

var importMerge bool

var importCmd = &cobra.Command{
	Use:   "import <file>",
	Short: "Import tasks from a JSON file",
	Long: `Import tasks from a JSON file containing an array of task objects.

By default, tasks that already exist (by ID) are skipped.
Use --merge to update existing tasks with the imported data.`,
	Args: cobra.ExactArgs(1),
	RunE: runImport,
}

func init() {
	rootCmd.AddCommand(importCmd)
	importCmd.Flags().BoolVar(&importMerge, "merge", false, "Update existing tasks instead of skipping")
}

func runImport(cmd *cobra.Command, args []string) error {
	filePath := args[0]

	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("failed to read file '%s': %w", filePath, err)
	}

	var tasks []models.Task
	if err := json.Unmarshal(data, &tasks); err != nil {
		return fmt.Errorf("failed to parse JSON: %w", err)
	}

	created, updated, skipped, err := ImportTasks(tasks, importMerge)
	if err != nil {
		return err
	}

	if IsJSONOutput() {
		OutputJSON(map[string]interface{}{
			"created": created,
			"updated": updated,
			"skipped": skipped,
			"total":   len(tasks),
		})
		return nil
	}

	fmt.Printf("Imported %d tasks: %d created, %d updated, %d skipped\n", len(tasks), created, updated, skipped)
	return nil
}

// ImportTasks imports a slice of tasks into the database.
// Returns counts of created, updated, and skipped tasks.
func ImportTasks(tasks []models.Task, merge bool) (created, updated, skipped int, err error) {
	database := db.GetDB()

	for _, t := range tasks {
		if t.ID == "" {
			// Task without an ID: always create (a new ID will be generated by BeforeCreate)
			if err := database.Create(&t).Error; err != nil {
				return created, updated, skipped, fmt.Errorf("failed to create task '%s': %w", t.Title, err)
			}
			created++
			continue
		}

		var existing models.Task
		result := database.Where("id = ?", t.ID).First(&existing)
		if result.Error != nil {
			// Task does not exist; create it
			if err := database.Create(&t).Error; err != nil {
				return created, updated, skipped, fmt.Errorf("failed to create task '%s': %w", t.ID, err)
			}
			created++
		} else if merge {
			// Task exists and merge mode is on; update it
			if err := database.Save(&t).Error; err != nil {
				return created, updated, skipped, fmt.Errorf("failed to update task '%s': %w", t.ID, err)
			}
			updated++
		} else {
			skipped++
		}
	}
	return created, updated, skipped, nil
}
