package cmd

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"regexp"
	"slices"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"gorm.io/gorm"

	"github.com/Giancarlos/guardrails/internal/db"
	"github.com/Giancarlos/guardrails/internal/models"
)

var importMerge bool

var importCmd = &cobra.Command{
	Use:   "import <file>",
	Short: "Import tasks from a JSON file",
	Long: `Import tasks from a JSON file containing an array of task objects.

Records are validated (ID format, title, status, priority, type) and the whole
import is applied atomically: if any record is invalid, nothing is imported.
Missing fields get the same defaults as 'gur create' (status open, priority 2, type task).

By default, tasks that already exist (by ID) are skipped.
Use --merge to update existing tasks: only fields present in the file are changed
(title, description, status, priority, type, assignee, notes, labels,
tokens_used, tokens_budget, context_summary), and each change is recorded in history.
Merging cannot close or reopen tasks; use 'gur close' or 'gur reopen'.`,
	Args: cobra.ExactArgs(1),
	RunE: runImport,
}

func init() {
	rootCmd.AddCommand(importCmd)
	importCmd.Flags().BoolVar(&importMerge, "merge", false, "Update existing tasks instead of skipping")
}

// importRecord pairs a decoded task with the set of JSON keys present in its source record
type importRecord struct {
	task   models.Task
	fields map[string]json.RawMessage
}

// importTaskIDPattern accepts gur- IDs (including hierarchical subtask IDs) without requiring
// the exact generated hex form, so previously exported or hand-written IDs still import
var importTaskIDPattern = regexp.MustCompile(`^gur-[a-z0-9]+(\.\d+)*$`)

// importTaskIDMaxLen matches the size of the tasks.id column
const importTaskIDMaxLen = 30

var importValidStatuses = map[string]bool{
	models.StatusOpen:       true,
	models.StatusInProgress: true,
	models.StatusClosed:     true,
	models.StatusArchived:   true,
}

var importValidTypes = map[string]bool{
	models.TypeTask:    true,
	models.TypeBug:     true,
	models.TypeFeature: true,
	models.TypeEpic:    true,
}

func runImport(cmd *cobra.Command, args []string) error {
	filePath := args[0]

	data, err := os.ReadFile(filePath)
	if err != nil {
		return fmt.Errorf("failed to read file '%s': %w", filePath, err)
	}

	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("failed to parse JSON: %w", err)
	}

	records := make([]importRecord, len(raw))
	for i, r := range raw {
		if err := json.Unmarshal(r, &records[i].task); err != nil {
			return fmt.Errorf("failed to parse record #%d: %w", i+1, err)
		}
		if err := json.Unmarshal(r, &records[i].fields); err != nil {
			return fmt.Errorf("failed to parse record #%d: %w", i+1, err)
		}
	}

	created, updated, skipped, err := importRecords(records, importMerge)
	if err != nil {
		return err
	}

	if IsJSONOutput() {
		OutputJSON(map[string]interface{}{
			"created": created,
			"updated": updated,
			"skipped": skipped,
			"total":   len(records),
		})
		return nil
	}

	fmt.Printf("Imported %d tasks: %d created, %d updated, %d skipped\n", len(records), created, updated, skipped)
	return nil
}

// ImportTasks imports a slice of tasks into the database.
// Every field that serializes to JSON is treated as present for --merge purposes.
// Returns counts of created, updated, and skipped tasks.
func ImportTasks(tasks []models.Task, merge bool) (created, updated, skipped int, err error) {
	records := make([]importRecord, len(tasks))
	for i, t := range tasks {
		records[i].task = t
		data, err := json.Marshal(t)
		if err != nil {
			return 0, 0, 0, fmt.Errorf("failed to encode task '%s': %w", t.ID, err)
		}
		if err := json.Unmarshal(data, &records[i].fields); err != nil {
			return 0, 0, 0, fmt.Errorf("failed to encode task '%s': %w", t.ID, err)
		}
	}
	return importRecords(records, merge)
}

// importRecords validates and applies records in a single transaction
func importRecords(records []importRecord, merge bool) (created, updated, skipped int, err error) {
	err = db.GetDB().Transaction(func(tx *gorm.DB) error {
		for i := range records {
			rec := &records[i]
			t := rec.task
			label := t.ID
			if label == "" {
				label = fmt.Sprintf("#%d", i+1)
			}

			if t.ID != "" && (len(t.ID) > importTaskIDMaxLen || !importTaskIDPattern.MatchString(t.ID)) {
				return fmt.Errorf("cannot import record %s: invalid task ID (expected gur-<lowercase letters/digits>, optionally .N subtask suffixes, max %d chars)", label, importTaskIDMaxLen)
			}

			var existing models.Task
			lookupErr := gorm.ErrRecordNotFound
			if t.ID != "" {
				lookupErr = tx.Where("id = ?", t.ID).First(&existing).Error
			}

			switch {
			case errors.Is(lookupErr, gorm.ErrRecordNotFound):
				if err := prepareImportedTask(&t, rec.fields); err != nil {
					return fmt.Errorf("cannot import record %s: %w", label, err)
				}
				// A task without an ID gets one generated by BeforeCreate
				if err := tx.Create(&t).Error; err != nil {
					return fmt.Errorf("failed to create task '%s': %w", label, err)
				}
				created++
			case lookupErr != nil:
				return fmt.Errorf("failed to look up task '%s': %w", label, lookupErr)
			case merge:
				if err := mergeImportedTask(tx, &existing, &t, rec.fields); err != nil {
					return fmt.Errorf("cannot merge record %s: %w", label, err)
				}
				if err := tx.Save(&existing).Error; err != nil {
					return fmt.Errorf("failed to update task '%s': %w", label, err)
				}
				updated++
			default:
				skipped++
			}
		}
		return nil
	})
	if err != nil {
		return 0, 0, 0, err
	}
	return created, updated, skipped, nil
}

// prepareImportedTask applies create-time defaults and validates a new task
func prepareImportedTask(t *models.Task, fields map[string]json.RawMessage) error {
	if strings.TrimSpace(t.Title) == "" {
		return errors.New("title is required")
	}
	if t.Status == "" {
		t.Status = models.StatusOpen
	}
	if !importValidStatuses[t.Status] {
		return fmt.Errorf("invalid status '%s': must be one of: open, in_progress, closed, archived", t.Status)
	}
	if _, ok := fields["priority"]; !ok {
		t.Priority = models.PriorityMedium
	}
	if t.Priority < 0 || t.Priority > 4 {
		return fmt.Errorf("invalid priority %d: must be 0 (critical) to 4 (lowest)", t.Priority)
	}
	if t.Type == "" {
		t.Type = models.TypeTask
	}
	if !importValidTypes[t.Type] {
		return fmt.Errorf("invalid type '%s': must be one of: task, bug, feature, epic", t.Type)
	}
	if t.TokensUsed < 0 || t.TokensBudget < 0 {
		return errors.New("token values must be zero or greater")
	}
	// Restored closed/archived tasks keep their close metadata; make sure ClosedAt is set
	if (t.Status == models.StatusClosed || t.Status == models.StatusArchived) && t.ClosedAt == nil {
		now := time.Now()
		t.ClosedAt = &now
	}
	return nil
}

// mergeImportedTask copies fields present in the record onto the existing task, recording each change
func mergeImportedTask(tx *gorm.DB, existing, incoming *models.Task, fields map[string]json.RawMessage) error {
	has := func(key string) bool {
		_, ok := fields[key]
		return ok
	}
	record := func(field, oldVal, newVal string) {
		models.RecordChange(tx, existing.ID, field, oldVal, newVal, "import")
	}

	if has("title") && incoming.Title != existing.Title {
		if strings.TrimSpace(incoming.Title) == "" {
			return errors.New("title cannot be empty")
		}
		record("title", existing.Title, incoming.Title)
		existing.Title = incoming.Title
	}
	if has("description") && incoming.Description != existing.Description {
		record("description", existing.Description, incoming.Description)
		existing.Description = incoming.Description
	}
	if has("status") && incoming.Status != "" && incoming.Status != existing.Status {
		movable := func(s string) bool { return s == models.StatusOpen || s == models.StatusInProgress }
		if !movable(existing.Status) || !movable(incoming.Status) {
			return fmt.Errorf("cannot change status from '%s' to '%s' via import (use 'gur close' or 'gur reopen')",
				existing.Status, incoming.Status)
		}
		record("status", existing.Status, incoming.Status)
		existing.Status = incoming.Status
	}
	if has("priority") && incoming.Priority != existing.Priority {
		if incoming.Priority < 0 || incoming.Priority > 4 {
			return fmt.Errorf("invalid priority %d: must be 0 (critical) to 4 (lowest)", incoming.Priority)
		}
		record("priority", fmt.Sprintf("%d", existing.Priority), fmt.Sprintf("%d", incoming.Priority))
		existing.Priority = incoming.Priority
	}
	if has("type") && incoming.Type != "" && incoming.Type != existing.Type {
		if !importValidTypes[incoming.Type] {
			return fmt.Errorf("invalid type '%s': must be one of: task, bug, feature, epic", incoming.Type)
		}
		record("type", existing.Type, incoming.Type)
		existing.Type = incoming.Type
	}
	if has("assignee") && incoming.Assignee != existing.Assignee {
		record("assignee", existing.Assignee, incoming.Assignee)
		existing.Assignee = incoming.Assignee
	}
	if has("notes") && incoming.Notes != existing.Notes {
		record("notes", existing.Notes, incoming.Notes)
		existing.Notes = incoming.Notes
	}
	if has("labels") && !slices.Equal(incoming.Labels, existing.Labels) {
		record("labels", strings.Join(existing.Labels, ","), strings.Join(incoming.Labels, ","))
		existing.Labels = incoming.Labels
	}
	if has("tokens_used") && incoming.TokensUsed != existing.TokensUsed {
		if incoming.TokensUsed < 0 {
			return errors.New("tokens_used must be zero or greater")
		}
		record("tokens_used", fmt.Sprintf("%d", existing.TokensUsed), fmt.Sprintf("%d", incoming.TokensUsed))
		existing.TokensUsed = incoming.TokensUsed
	}
	if has("tokens_budget") && incoming.TokensBudget != existing.TokensBudget {
		if incoming.TokensBudget < 0 {
			return errors.New("tokens_budget must be zero or greater")
		}
		record("tokens_budget", fmt.Sprintf("%d", existing.TokensBudget), fmt.Sprintf("%d", incoming.TokensBudget))
		existing.TokensBudget = incoming.TokensBudget
	}
	if has("context_summary") && incoming.ContextSummary != existing.ContextSummary {
		record("context_summary", existing.ContextSummary, incoming.ContextSummary)
		existing.ContextSummary = incoming.ContextSummary
	}
	return nil
}
